audits:
  - axe
  - size
  - lighthouse
  - unused-source
  - heap-snapshot

configs:
  buildDir: dist/example-angular
  heap-snapshot:
    threshold:
      Nodes: 81
  lighthouse:
    threshold:
      accessibility: 100
      'best-practices': 100
      performance: 1
      pwa: 20
  size:
    threshold:
      - path: dist/example-angular/main-*.js
        maxSize: 3 KB
      - path: dist/example-angular/polyfills-es5.js
        maxSize: 90 KB
      - path: dist/example-angular/polyfills-es2015.js
        maxSize: 45 KB
      - path: dist/example-angular/runtime-*.js
        maxSize: 1.75 KB
      - path: dist/example-angular/styles-*.js
        maxSize: 5.25 KB
      - path: dist/example-angular/vendor-*.js
        maxSize: 700 KB

plugins:
  - plugin: '@modus/gimbal-plugin-axe'
    thresholds:
      landmark-one-main: moderate
      region: moderate
  - '@modus/gimbal-plugin-last-value'
  - plugin: '@modus/gimbal-plugin-sqlite'
    lastValue: true
