version: 2

audits:
  heap-snapshot:
    threshold:
      Nodes: 83
  lighthouse:
    threshold:
      accessibility: 100
      "best-practices": 100
      performance: 1
      pwa: 19
      seo: 90
  size:
    threshold:
      - path: dist/example-angular/main-*.js
        maxSize: 3 KB
      - path: dist/example-angular/polyfills-es5.js
        maxSize: 90 KB
      - path: dist/example-angular/polyfills-es2015.js
        maxSize: 45 KB
      - path: dist/example-angular/runtime-*.js
        maxSize: 1.75 KB
      - path: dist/example-angular/styles-*.js
        maxSize: 5.25 KB
      - path: dist/example-angular/vendor-*.js
        maxSize: 700 KB
      - path: dist/example-angular/
        maxSize: 17 MB
      - path: dist/
        maxSize: 17 MB
  unused-source: true
  axe:
    thresholds:
      landmark-one-main: moderate
      region: moderate
  source-map-explorer:
    bundles:
      - path: "main*.js"
        thresholds:
          $_lazy_route_resource lazy namespace object: 600 B
          src/app/app.component.html: 1.5 KB
          src/app/app*: 600 B
          src/environments/environment.ts: 550 B
          src/main.ts: 1.5 KB
          <unmapped>: 5.5 KB
      - path: "styles*.js"
        thresholds:
          node_modules/style-loader/lib/addStyles.js: 10 KB
          node_modules/style-loader/lib/urls.js: 3 KB
          src/styles.css: 500 B
          src/styles.css?b364: 800 B
          <unmapped>: 2 KB
      - "!**/polyfills*.js"
      - "!**/runtime*.js"
      - "!**/vendor*.js"

configs:
  comment:
    header: Angular Example
    onlyFailures: true
  buildDir: dist/example-angular

outputs:
  html: artifacts/gimbal.html
  json: artifacts/gimbal.json
  markdown: artifacts/gimbal.md

plugins:
  - "@modus/gimbal-plugin-axe"
  - "@modus/gimbal-plugin-source-map-explorer"
  - "@modus/gimbal-plugin-last-value"
  - plugin: "@modus/gimbal-plugin-mysql"
    enabled: ${env:CI, true, false}
    commandPrefix:
      - angular-example-${env:GITHUB_REPOSITORY}-${env:GITHUB_REF}
      - angular-example
    lastValue:
      database: gimbal_github
    host: ${env:GIMBAL_MYSQL_HOST}
    password: ${env:GIMBAL_MYSQL_PASSWORD}
    user: ${env:GIMBAL_MYSQL_USERNAME}
  # - plugin: '@modus/gimbal-plugin-sqlite'
  #   enabled: ${env:CI, true, false}
  #   commandPrefix:
  #     - angular-example-${env:GITHUB_REPOSITORY}-${env:GITHUB_REF}
  #     - angular-example
  #   lastValue: true
