audits:
  - axe
  - size
  - lighthouse
  - unused-source
  - heap-snapshot
  - source-map-explorer

configs:
  buildDir: dist/example-angular
  heap-snapshot:
    threshold:
      Nodes: 81
  lighthouse:
    threshold:
      accessibility: 100
      'best-practices': 100
      performance: 1
      pwa: 20
  size:
    threshold:
      - path: dist/example-angular/main-*.js
        maxSize: 3 KB
      - path: dist/example-angular/polyfills-es5.js
        maxSize: 90 KB
      - path: dist/example-angular/polyfills-es2015.js
        maxSize: 45 KB
      - path: dist/example-angular/runtime-*.js
        maxSize: 1.75 KB
      - path: dist/example-angular/styles-*.js
        maxSize: 5.25 KB
      - path: dist/example-angular/vendor-*.js
        maxSize: 700 KB

outputs:
  html: artifacts/gimbal.html
  json: artifacts/gimbal.json
  markdown: artifacts/gimbal.md

plugins:
  - plugin: '@modus/gimbal-plugin-axe'
    thresholds:
      landmark-one-main: moderate
      region: moderate
  - plugin: '@modus/gimbal-plugin-source-map-explorer'
    bundles:
      - path: 'main*.js'
        thresholds:
          $_lazy_route_resource lazy namespace object: 600 B
          src/app/app.component.html: 1.5 KB
          src/app/app*: 600 B
          src/environments/environment.ts: 550 B
          src/main.ts: 1.5 KB
          <unmapped>: 5.5 KB
      - path: 'styles*.js'
        thresholds:
          node_modules/style-loader/lib/addStyles.js: 10 KB
          node_modules/style-loader/lib/urls.js: 3 KB
          src/styles.css: 500 B
          src/styles.css?b364: 800 B
          <unmapped>: 2 KB
      - '!**/polyfills*.js'
      - '!**/runtime*.js'
      - '!**/vendor*.js'
  - '@modus/gimbal-plugin-last-value'
  - plugin: '@modus/gimbal-plugin-sqlite'
    lastValue: true
