audits:
  heap-snapshot: true
  lighthouse: true
  size: true
  unused-source: true
  axe:
    thresholds:
      bypass: serious
      landmark-one-main: moderate
      page-has-heading-one: moderate
  source-map-explorer:
    bundles:
      - path: "**/main.*.js"
        thresholds:
          App.js: 450 B
          index.js: 100 B
          logo.svg: 250 B
          serviceWorker.js: 300 B
          <unmapped>: 150 B
      - path: "**/2.*.js"
        thresholds:
          react/index.js: 50 B
          object-assign/index.js: 1 KB
          react-dom/index.js: 300 B
          react/cjs/react.production.min.js: 7 KB
          react-dom/cjs/react-dom.production.min.js: 110 KB
          scheduler/index.js: 50 B
          scheduler/cjs/scheduler.production.min.js: 5 KB
          webpack/builtin/global.js: 150 B
          <unmapped>: 150 B
      - "!precache-manifest*"
      - "!service-worker.js"
      - "!**/runtime*.js"

configs:
  comment:
    header: React Example
    onlyFailures: true

outputs:
  html: artifacts/gimbal.html
  json: artifacts/gimbal.json
  markdown: artifacts/gimbal.md

plugins:
  - "@modus/gimbal-plugin-axe"
  - "@modus/gimbal-plugin-source-map-explorer"
  - "@modus/gimbal-plugin-last-value"
  - plugin: "@modus/gimbal-plugin-mysql"
    enabled: ${env:CI, true, false}
    commandPrefix:
      - react-example-${env:GITHUB_REPOSITORY}-${env:GITHUB_REF}
      - react-example
    lastValue:
      database: gimbal_github
    host: ${env:GIMBAL_MYSQL_HOST}
    password: ${env:GIMBAL_MYSQL_PASSWORD}
    user: ${env:GIMBAL_MYSQL_USERNAME}
# - plugin: '@modus/gimbal-plugin-sqlite'
#   enabled: ${env:CI, true, false}
#   commandPrefix:
#     - react-example-${env:GITHUB_REPOSITORY}-${env:GITHUB_REF}
#     - react-example
#   lastValue: true
