name: CI

on: push

jobs:
  test-examples:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install
        uses: nuxt/actions-yarn@master
        with:
          args: install
      - name: Build Examples
        uses: nuxt/actions-yarn@master
        with:
          args: build:examples
      - name: Test Angular example
        run: yarn --cwd examples/angular gimbal --verbose
        env:
          GIMBAL_MYSQL_HOST: ${{ secrets.GIMBAL_MYSQL_HOST }}
          GIMBAL_MYSQL_PASSWORD: ${{ secrets.GIMBAL_MYSQL_PASSWORD }}
          GIMBAL_MYSQL_USERNAME: ${{ secrets.GIMBAL_MYSQL_USERNAME }}
          GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test React example
        run: yarn --cwd examples/react gimbal --verbose
        env:
          GIMBAL_MYSQL_HOST: ${{ secrets.GIMBAL_MYSQL_HOST }}
          GIMBAL_MYSQL_PASSWORD: ${{ secrets.GIMBAL_MYSQL_PASSWORD }}
          GIMBAL_MYSQL_USERNAME: ${{ secrets.GIMBAL_MYSQL_USERNAME }}
          GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Test React Router example
        run: yarn --cwd examples/react-router gimbal --verbose
        env:
          GIMBAL_MYSQL_HOST: ${{ secrets.GIMBAL_MYSQL_HOST }}
          GIMBAL_MYSQL_PASSWORD: ${{ secrets.GIMBAL_MYSQL_PASSWORD }}
          GIMBAL_MYSQL_USERNAME: ${{ secrets.GIMBAL_MYSQL_USERNAME }}
          GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
