name: CI

on: push

# GitHub Actions don't support cache yet so need...
# to install first and run steps after. This causes
# steps to run sequentially instead of parallel tho.

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install
        uses: nuxt/actions-yarn@master
        with:
          args: install
      - name: Lint
        uses: nuxt/actions-yarn@master
        with:
          args: lint
      - name: Test
        uses: nuxt/actions-yarn@master
        with:
          args: test
      - name: Build
        uses: nuxt/actions-yarn@master
        with:
          args: build
