name: Test

on: push

# GitHub Actions don't support cache yet so need...
# to install first and run steps after. This causes
# steps to run sequentially instead of parallel tho.

jobs:
  lint-test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.1.0
        with:
          node-version: 14
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
